dataset_name: drb
edge_data:
  - file_name: edges_0.csv
    etype: ["instruction", "control", "instruction"]
  - file_name: edges_1.csv
    etype: ["instruction", "call", "instruction"]
  - file_name: edges_2.csv
    etype: ["instruction", "data", "variable"]
  - file_name: edges_3.csv
    etype: ["variable", "data", "varray"]
  - file_name: edges_4.csv
    etype: ["instruction", "data", "vvector"]
  - file_name: edges_5.csv
    etype: ["variable", "data", "instruction"]
  - file_name: edges_6.csv
    etype: ["varray", "data", "instruction"]
  - file_name: edges_7.csv
    etype: ["varray", "data", "varray"]
  - file_name: edges_8.csv
    etype: ["vvector", "data", "vvector"]
  - file_name: edges_9.csv
    etype: ["vvector", "data", "instruction"]
  - file_name: edges_10.csv
    etype: ["constant", "data", "instruction"]
  - file_name: edges_11.csv
    etype: ["carray", "data", "instruction"]
  - file_name: edges_12.csv
    etype: ["carray", "data", "carray"]
  - file_name: edges_13.csv
    etype: ["cvector", "data", "instruction"]
  - file_name: edges_14.csv
    etype: ["cvector", "data", "cvector"]
  - file_name: edges_15.csv
    etype: ["instruction", "data", "constant"]
  - file_name: edges_16.csv
    etype: ["instruction", "data", "carray"]
  - file_name: edges_17.csv
    etype: ["instruction", "data", "cvector"]
node_data:
  - file_name: nodes_0.csv
    ntype: instruction
  - file_name: nodes_1.csv
    ntype: variable
  - file_name: nodes_2.csv
    ntype: constant
  - file_name: nodes_3.csv
    ntype: varray
  - file_name: nodes_4.csv
    ntype: vvector
  - file_name: nodes_5.csv
    ntype: carray
  - file_name: nodes_6.csv
    ntype: cvector